apiVersion: batch/v1
kind: CronJob
metadata:
  name: report-generator
  namespace: dev
  labels:
    job: report-generator
spec:
  schedule: "*/5 * * * *"   # every 5 minutes
  concurrencyPolicy: Forbid # Skip if previous still running
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            job: report-generator
        spec:
          restartPolicy: OnFailure
          containers:
            - name: report
              image: busybox:1.36
              command: ["sh", "-c", "date; echo Generating report...; sleep 5; echo Done"]
              resources:
                requests:
                  cpu: "100m"
                  memory: "128Mi"
                limits:
                  cpu: "300m"
                  memory: "256Mi"
